[ota]
#max length of version_hardware is 15 bytes
version_hardware = "QCC74X_Module_v1.1"
#max length of version_software is 15 bytes
version_software = "EVENT_V1.1.1"
version_header = "QCC74X_OTA_Ver1.0"
