#ifndef __QCC74x_EFLASH_LOADER_H__
#define __QCC74x_EFLASH_LOADER_H__

#include "qcc74x_eflash_loader_interface.h"
#include "qcc74x_eflash_loader_cmds.h"
#include "qcc74x_eflash_loader_uart.h"
#include "qcc74x_eflash_loader_usb.h"

/*error code definition*/
typedef enum tag_eflash_loader_error_code_t {
    QCC74x_EFLASH_LOADER_SUCCESS = 0x00,

    /*flash*/
    QCC74x_EFLASH_LOADER_FLASH_INIT_ERROR = 0x0001,
    QCC74x_EFLASH_LOADER_FLASH_ERASE_PARA_ERROR = 0x0002,
    QCC74x_EFLASH_LOADER_FLASH_ERASE_ERROR = 0x0003,
    QCC74x_EFLASH_LOADER_FLASH_WRITE_PARA_ERROR = 0x0004,
    QCC74x_EFLASH_LOADER_FLASH_WRITE_ADDR_ERROR = 0x0005,
    QCC74x_EFLASH_LOADER_FLASH_WRITE_ERROR = 0x0006,
    QCC74x_EFLASH_LOADER_FLASH_BOOT_PARA_ERROR = 0x0007,
    QCC74x_EFLASH_LOADER_FLASH_SET_PARA_ERROR = 0x0008,
    QCC74x_EFLASH_LOADER_FLASH_READ_STATUS_REG_ERROR = 0x0009,
    QCC74x_EFLASH_LOADER_FLASH_WRITE_STATUS_REG_ERROR = 0x000A,
    QCC74x_EFLASH_LOADER_FLASH_DECOMPRESS_WRITE_ERROR = 0x000B,
    QCC74x_EFLASH_LOADER_FLASH_WRITE_XZ_ERROR = 0x000C,

    /*cmd*/
    QCC74x_EFLASH_LOADER_CMD_ID_ERROR = 0x0101,
    QCC74x_EFLASH_LOADER_CMD_LEN_ERROR = 0x0102,
    QCC74x_EFLASH_LOADER_CMD_CRC_ERROR = 0x0103,
    QCC74x_EFLASH_LOADER_CMD_SEQ_ERROR = 0x0104,

    /*image*/
    QCC74x_EFLASH_LOADER_IMG_BOOTHEADER_LEN_ERROR = 0x0201,
    QCC74x_EFLASH_LOADER_IMG_BOOTHEADER_NOT_LOAD_ERROR = 0x0202,
    QCC74x_EFLASH_LOADER_IMG_BOOTHEADER_MAGIC_ERROR = 0x0203,
    QCC74x_EFLASH_LOADER_IMG_BOOTHEADER_CRC_ERROR = 0x0204,
    QCC74x_EFLASH_LOADER_IMG_BOOTHEADER_ENCRYPT_NOTFIT = 0x0205,
    QCC74x_EFLASH_LOADER_IMG_BOOTHEADER_SIGN_NOTFIT = 0x0206,
    QCC74x_EFLASH_LOADER_IMG_SEGMENT_CNT_ERROR = 0x0207,
    QCC74x_EFLASH_LOADER_IMG_AES_IV_LEN_ERROR = 0x0208,
    QCC74x_EFLASH_LOADER_IMG_AES_IV_CRC_ERROR = 0x0209,
    QCC74x_EFLASH_LOADER_IMG_PK_LEN_ERROR = 0x020a,
    QCC74x_EFLASH_LOADER_IMG_PK_CRC_ERROR = 0x020b,
    QCC74x_EFLASH_LOADER_IMG_PK_HASH_ERROR = 0x020c,
    QCC74x_EFLASH_LOADER_IMG_SIGNATURE_LEN_ERROR = 0x020d,
    QCC74x_EFLASH_LOADER_IMG_SIGNATURE_CRC_ERROR = 0x020e,
    QCC74x_EFLASH_LOADER_IMG_SECTIONHEADER_LEN_ERROR = 0x020f,
    QCC74x_EFLASH_LOADER_IMG_SECTIONHEADER_CRC_ERROR = 0x0210,
    QCC74x_EFLASH_LOADER_IMG_SECTIONHEADER_DST_ERROR = 0x0211,
    QCC74x_EFLASH_LOADER_IMG_SECTIONDATA_LEN_ERROR = 0x0212,
    QCC74x_EFLASH_LOADER_IMG_SECTIONDATA_DEC_ERROR = 0x0213,
    QCC74x_EFLASH_LOADER_IMG_SECTIONDATA_TLEN_ERROR = 0x0214,
    QCC74x_EFLASH_LOADER_IMG_SECTIONDATA_CRC_ERROR = 0x0215,
    QCC74x_EFLASH_LOADER_IMG_HALFBAKED_ERROR = 0x0216,
    QCC74x_EFLASH_LOADER_IMG_HASH_ERROR = 0x0217,
    QCC74x_EFLASH_LOADER_IMG_SIGN_PARSE_ERROR = 0x0218,
    QCC74x_EFLASH_LOADER_IMG_SIGN_ERROR = 0x0219,
    QCC74x_EFLASH_LOADER_IMG_DEC_ERROR = 0x021a,
    QCC74x_EFLASH_LOADER_IMG_ALL_INVALID_ERROR = 0x021b,

    /*IF*/
    QCC74x_EFLASH_LOADER_IF_RATE_LEN_ERROR = 0x0301,
    QCC74x_EFLASH_LOADER_IF_RATE_PARA_ERROR = 0x0302,
    QCC74x_EFLASH_LOADER_IF_PASSWORDERROR = 0x0303,
    QCC74x_EFLASH_LOADER_IF_PASSWORDCLOSE = 0x0304,

    /*efuse*/
    QCC74x_EFLASH_LOADER_EFUSE_WRITE_PARA_ERROR = 0x0401,
    QCC74x_EFLASH_LOADER_EFUSE_WRITE_ADDR_ERROR = 0x0402,
    QCC74x_EFLASH_LOADER_EFUSE_WRITE_ERROR = 0x0403,
    QCC74x_EFLASH_LOADER_EFUSE_READ_PARA_ERROR = 0x0404,
    QCC74x_EFLASH_LOADER_EFUSE_READ_ADDR_ERROR = 0x0405,
    QCC74x_EFLASH_LOADER_EFUSE_READ_ERROR = 0x0406,
    QCC74x_EFLASH_LOADER_EFUSE_READ_MAC_ERROR = 0x0407,

    /*MISC*/
    QCC74x_EFLASH_LOADER_PLL_ERROR = 0xfffc,
    QCC74x_EFLASH_LOADER_INVASION_ERROR = 0xfffd,
    QCC74x_EFLASH_LOADER_POLLING = 0xfffe,
    QCC74x_EFLASH_LOADER_FAIL = 0xffff,

} eflash_loader_error_code_t;

/** private definition**/
#define EFLASH_LOADER_CMD_DISABLE   0x000
#define EFLASH_LOADER_CMD_ENABLE    0x001
#define QCC74x_EFLASH_LOADER_CMD_ACK  0x00004B4F
#define QCC74x_EFLASH_LOADER_CMD_NACK 0x00004C46

#define QCC74x_EFLASH_LOADER_EFUSE0_SIZE 128

/*max data payload in command*/
#define QCC74x_EFLASH_LOADER_READBUF_SIZE     (1024 * 16 + 8)
#define QCC74x_EFLASH_LOADER_WRITEBUF_SIZE    QCC74x_EFLASH_LOADER_READBUF_SIZE
#define QCC74x_EFLASH_LOADER_CMD_DATA_MAX_LEN (QCC74x_EFLASH_LOADER_READBUF_SIZE - 0x04) //cmd+rsvd+len(2bytes)

#define MAXOF(a, b)          ((a) > (b) ? (a) : (b))
#define OFFSET(TYPE, MEMBER) ((uint32_t)(&(((TYPE *)0)->MEMBER)))

uint8_t bootrom_read_boot_mode(void);
void qcc74x_eflash_loader_init_uart_gpio(uint8_t eflash_loader_uart_pin_select);
void qcc74x_eflash_loader_deinit_uart_gpio_do(uint8_t eflash_loader_uart_pin_select);
void qcc74x_eflash_loader_deinit_uart_gpio(uint8_t eflash_loader_uart_pin_select);
void qcc74x_eflash_loader_init_flash_gpio(uint8_t flash_cfg);

#endif
